version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    entrypoint: init/docker-entrypoint
    environment:
      - EXTERNAL_PORT=8080
      - GITHUB_ACTIONS=${GITHUB_ACTIONS}
    ports: 
      - 8080:80
      - 8443:443
    volumes:
      - ./docker-entrypoint:/init/docker-entrypoint
      - ./init:/init/init
      - ./test.rb:/init/test.rb
      - ./config:/config
  test:
    image: mcr.microsoft.com/powershell:latest
    environment:
      - GITHUB_ACTIONS=${GITHUB_ACTIONS}
    command: >
      pwsh -c "Install-Module Pester,PSScriptAnalyzer,Psake -Scope CurrentUser -force";
      pwsh -File /PSGitlab/run-tests.ps1
    container_name: gitlab-ps
    volumes:
      - ../.:/PSGitlab
      - ./config:/config
    links:
      - gitlab